-- MySQL Script generated by MySQL Workbench
-- Tue Apr 30 10:34:48 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reconocimientofacial` DEFAULT CHARACTER SET utf8 ;
USE `reconocimientofacial` ;

-- -----------------------------------------------------
-- Table `mydb`.`fichapersonal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reconocimientofacial`.`fichapersonal` (
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(50) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `telefono` INT(9) NOT NULL,
  `direccion` VARCHAR(50),
  `nivelConfidencialidad` INT NOT NULL,
  `email` VARCHAR(50) UNIQUE,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reconocimientofacial`.`usuario` (
  `nivelseguridad` INT NOT NULL,
  `nombreusuario` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `puesto` VARCHAR(20),
  `fichapersonal` VARCHAR(9),
  PRIMARY KEY (`nombreusuario`),
  INDEX `fk_usuario_fichapersonal1_idx` (`fichapersonal` ASC),
  CONSTRAINT `fk_usuario_fichapersonal1`
    FOREIGN KEY (`fichapersonal`)
    REFERENCES `reconocimientofacial`.`fichapersonal` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reconocimientofacial`.`imagen` (
  `id` int,
  `imagen` BLOB NOT NULL,
  `cara` tinyint NOT NULL,
  `fichapersonal` VARCHAR(9),
  PRIMARY KEY (`id`),
  INDEX `fk_imagen_fichapersonal1_idx` (`fichapersonal` ASC),
  CONSTRAINT `fk_imagen_fichapersonal1`
    FOREIGN KEY (`fichapersonal`)
    REFERENCES `reconocimientofacial`.`fichapersonal` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
